apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:E/vPdTAVPxTC497w+xwLCVrz,iv:QoltIFYZgvGpwxWYuXxRu2XVm8kUsGSr9E0xmCu2aTc=,tag:4dGUTeqxJw1eOsRvLUDB7A==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:aBK36wT3utVHlLltTQMPylSa8cB1wGtXgXTrNehjdJudxV/N7Q==,iv:+x8r90b8SrggdG3Uh5pNoP5Z2Mys2sqMoIBC3yaneWs=,tag:f0w7b6U71PEBSpeRzfCPhw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:vJM1FVW+vTD8p61gsxiiJ6guag==,iv:WT5HhvhCytGKChULKx8cDDFOPD1MLdHApV/wGoeJcYY=,tag:pORvcT2o+c/sDNi/7Ciriw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19crq4cyp68d9g5dmdun32zg79dfmkk7r6cp5v5c5nnfytm9hpugsu2nn26
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Sk01ZXF2RURKWXE3N3A4
            VE5rTE0rNXlTb3M4Wk14Y1lDTVNhSi8vZUJRCnZCY3ZkeWg3Mis2NHN3NXNQTDlI
            QlM1Tk04eVBZR1B3OXE2Q2V6ZXM5KzQKLS0tIGdLa1hjRUt0amR5OHlKd20wWVlQ
            M1lmSzBlVnlFcFZibEd5Z3lta0dYRU0KXSG6zJpIBxhqtMWdi19dBJuyfbDXOMo6
            oJzfam8yNasQMt3d4IJpt9QveW+MTXX+/SpzICOjQbaPNYkvkeZogA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-19T23:43:59Z"
    mac: ENC[AES256_GCM,data:NNfpkH4sINCVGT4qqjsu4hAmqZzslHKA5MSxFY74Kbf7ckm3RJup3A4MIFW4H9+vv3BK2FIPGzYF6I6lCeu0ibffEw7nnDsX22HGVt/6l+2fLExynJQ4vWwLLSybQ1szgcUg2I/my/xdkv1lshoGzm2f4ymBJ/D3B8xXY5T6ySo=,iv:FmuECz62ENhM5My+K/Dp9nB1PrjAng5n0tq98q/ANIM=,tag:QWnVsnYf2bDn6OGImDwiDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
