---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age19crq4cyp68d9g5dmdun32zg79dfmkk7r6cp5v5c5nnfytm9hpugsu2nn26
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age19crq4cyp68d9g5dmdun32zg79dfmkk7r6cp5v5c5nnfytm9hpugsu2nn26
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age19crq4cyp68d9g5dmdun32zg79dfmkk7r6cp5v5c5nnfytm9hpugsu2nn26
